// * next.js imports *
import Head from 'next/head';

// * third party library imports *
// import PropTypes from 'prop-types';

// * custom component imports *
import AppFooter from '@/components/app-footer/AppFooter';
import AppHeader from '@/components/app-header/AppHeader';
import AppLogin from '@/components/app-login/AppLogin';

export default function Login() {
  return (
    <>
      <Head>
        <title>Employment App – Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader />
      <main>
        <AppLogin />
      </main>
      <AppFooter />
    </>
  );
}
