// * next.js imports *
import Head from 'next/head';

// * third party library imports *
import PropTypes from 'prop-types';

// * custom component imports *
import AppFooter from '@/components/app-footer/AppFooter';
import AppHeader from '@/components/app-header/AppHeader';

export default function Employer() {
  return (
    <>
      <Head>
        <title>Employment App – Employer Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader />
      <main>
        Employer Signup Page
      </main>
      <AppFooter />
    </>
  );
}

Employer.propTypes = {
};
