// * next.js imports *
import Head from 'next/head';

// * react-bootstrap imports *
import Col from 'react-bootstrap/Col';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';

// * custom component imports *
import AppFooter from '@/components/app-footer/AppFooter';
import AppHeader from '@/components/app-header/AppHeader';
import FormJobSeekerSignup from '@/components/forms/FormJobSeekerSignup';

export default function JobSeeker() {
  return (
    <>
      <Head>
        <title>Employment App – Job Seeker Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader />
      <main>
        <Container>
          <Row className="justify-content-lg-center">
            <Col xs={12} lg={8} xl={6}>
              <div className="text-center">
                <h1>Job Seeker Signup</h1>
                <p>Please fill out the form below to create your account.</p>
              </div>
            </Col>
          </Row>
        </Container>
        <FormJobSeekerSignup />
      </main>
      <AppFooter />
    </>
  );
}
